### ISSUE TITLE
Cannot compile in Matlab 2014b on OS X 10.8.5

### ISSUE THREAD

**Issue by napopa** [kyamagu/matlab-sqlite3-driver#4]
If i try to compile using mex i get the following error 
```
sqlite3.make

mex -c -Iinclude src/sqlite3/sqlite3.c -outdir src/sqlite3
Building with 'Xcode with Clang'.
MEX completed successfully.
mex -Iinclude src/api.cc src/sqlite3mex.cc src/sqlite3/sqlite3.o -output +sqlite3/private/libsqlite3_
Building with 'Xcode Clang++'.
Error using mex
In file included from /Users/napopa/Downloads/matlab-sqlite3-driver-master/src/api.cc:6:
In file included from include/mexplus.h:9:
In file included from include/mexplus/arguments.h:33:
In file included from include/mexplus/mxarray.h:53:
include/mexplus/mxtypes.h:10:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^
1 error generated.


Error in sqlite3.make>dispAndEval (line 40)
  eval(command);

Error in sqlite3.make (line 14)
      dispAndEval([...

```

**Comment by napopa** [comment]
Ok, I followed the guidelines here and it worked

https://bcslib.googlecode.com/hg/bcslib/matlab/instructions.txt

and created a modified mexopts.sh file in my ~/.matlab/R2014b folder.
